import './header-mobile';
import './vendor';
import './dropdown-menu';
import './once-slider';
import './catalog';
import './triple-slider';
import './fives-slider';
import './contacts-map';
import './tabs';
