import './vendor';
import './header-mobile';
import './dropdown-menu';
import './once-slider';
import './catalog';
import './triple-slider';
import './fives-slider';
import './tabs';
import './popup';
import 'jquery.nice-number/src/jquery.nice-number';
import $ from "jquery";
$('input[type="number"]').niceNumber();
import './contacts-map';
